spring:
  application:
    name: VISA
  datasource:
    url: jdbc:mariadb://172.16.0.3:3308/visa
    #url: jdbc:mariadb://127.0.0.1:3308/visa
    password: q1w2e3r4t5
    username: root
    driver-class-name: org.mariadb.jdbc.Driver
    hikari:
      maximum-pool-size: 15
      minimum-idle: 5
      idle-timeout: 30000
      max-lifetime: 1800000
      connection-timeout: 30000
      pool-name: NecropolisHikariCP